### ISSUE TITLE
No way to delete comics

### ISSUE THREAD

**Issue by Hoplake** [Tenma-Server/Tenma#29]
I renamed some comics, because of the names conflicting with other comics, now when I importer Tenma has duplicate comics, one with the old file name and one with the new. There seems to be no way in the UI (or wiki) to remove certain comics (or comics with files missing, or even just remove everything and start over).

**Comment by hmhrex** [comment]
Since this is built on Django, you can login to the backend to delete stuff out. That can be found at `[tenmaurl]/admin`. I'm going to make this a feature request for the front end though. Thanks!

**Comment by hmhrex** [comment]
This functionality has been added.
