### ISSUE TITLE
Python manage.py importerror

### ISSUE THREAD

**Issue by Saltystew** [Tenma-Server/Tenma#35]
![shot_170821_194255](https://user-images.githubusercontent.com/20447447/29542540-332955bc-86a9-11e7-8d96-dd6df4b488ae.png)

Any idea what's wrong?

**Comment by hmhrex** [comment]
That looks like you might be using python 2.x rather than python 3.x. If you run `python -v` while in the virtual environment, what do you get?

**Comment by Saltystew** [comment]
It appears your right, which confuses me because outside of the virtual environment it says version 3.6.2.

How can I specify or change the python that the virtual environment points to?

**Comment by hmhrex** [comment]
Using the `-p` switch when creating the virtual environment: https://virtualenv.pypa.io/en/stable/reference/#cmdoption-p
