### ISSUE TITLE
Error When Trying to Read Any Issue (Docker)

### ISSUE THREAD

**Issue by ianc125** [Tenma-Server/Tenma#36]
Request Method: | GET
-- | --
http://tenma.xxxxx.com/issue/178/read
1.10.1
OSError
cannot identify image file '/tenma/media/temp/178/ComicInfo.xml'
/usr/lib/python3.6/site-packages/PIL/Image.py in open, line 2349
/usr/bin/python3
3.6.1
['/tenma',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/lib/python3.6/site-packages',  '/tenma']
Mon, 28 Aug 2017 12:31:39 -0500

Error during template rendering

In template /tenma/comics/templates/comics/read.html, error at line 25
cannot identify image file '/tenma/media/temp/178/ComicInfo.xml'

15 | </div>
-- | --
{% endblock %}
 
{% block page-type %}reader{% endblock %}
 
{% block content %}
 
<div class="flexslider reader-slider">
<div class="issue-data" data-id="{{ issue.id }}" data-leaf="{{ issue.leaf }}"></div>
<ul class="slides">
{% for item in issue.page_set.pages %}
{% with mediaurl=issue.page_set.mediaurl %}
<li class="page page-{{ forloop.counter }}">
<img src="{% static 'comics/image-loading.png' %}" data-source="{{ mediaurl }}{{ item }}" class="lazy-load" alt="Page #{{ forloop.counter }}" >
</li>
{% endwith %}
{% endfor %}
</ul>
</div>
 
{% endblock content %}

**Comment by hmhrex** [comment]
Interesting. Only image files should be indexed when looking in comic files. Somehow the ComicInfo.xml file slipped through. I'll test this out.

**Comment by ianc125** [comment]
That would explain why its happening on them all.

Thats exactly what it is, I ripped out the ComicInfo.xml file and it opened up fine on my test file.

**Comment by hmhrex** [comment]
Ok. I'll try and get a fix for this at some point this week. If you know a little python, I'll accept a pull-request! It seems like an easy enough fix. Unfortunately I have a very busy week.

**Comment by ianc125** [comment]
If I get a chance I'll take a peek - I should know enough python to manage. Busy here too this week. Similar jobs btw lol.
