### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by calgara12** [Tenma-Server/Tenma#45]
Hey, 

First of all: Thank you so much for this application.

I followed the instructions to install everything properly. But when i try to click the Import Comics Button i get the message sqlite3.OperationalError: database is locked

Do you have an idea what i could to to solve this issue? 

Thanks in advance! :)

**Comment by hmhrex** [comment]
This is a SQLite3 error. It means that when you're trying to access the database, it's in use and being locked for that use. This shouldn't very often. You could try restarting the services that Tenma uses to see if that fixes the issue.

If you're not using the [Docker image](https://github.com/Tenma-Server/Docker), you could also try increasing the database timeout value on line [`130` in `settings.py`](https://github.com/Tenma-Server/Tenma/blob/master/tenma/settings.py).

If you're still having issues, please post answers to the following:
1. What operating system is Tenma running on?
2. What version of Python is running on the system?

**Comment by calgara12** [comment]
Restarting the services seemed to have fixed the issue. Thanks!!!!

**Comment by hmhrex** [comment]
Glad to hear that worked for you!
