### ISSUE TITLE
Comic pages out of order

### ISSUE THREAD

**Issue by BigJArm** [Tenma-Server/Tenma#59]
I have the docker version installed and overall I love it. However I have quite a few comics that the pages are showing out of order in tenma but they are numbers correctly in the cbr and work fine in other readers

**Comment by hmhrex** [comment]
Very interesting. Are the file names using a formatted numbering system (001, 002, 003, ... 021, 022), or is it just numbered regularly (1, 2, 3, ... 21, 22)?

**Comment by BigJArm** [comment]
They all use the 000, 001, 002 format. I'm attaching 3 images of the cbr files (I would upload the files themselves but the max file size to upload is 10mb). The first 2 play out of order both starting with page 4 (file number 003 since it starts with 000). Issue 146 Goes page 4, 5, 1 ... and Issue 147 goes 4, 5, 6, 7, 8, 9, 10, 1 ... and Issue 148 reads in the correct order. 

I'm happy to provide any other information or pull any files you may need. 

![image](https://user-images.githubusercontent.com/4229961/33840454-30803e38-de52-11e7-9399-d3dbb04a3dec.png)

![image](https://user-images.githubusercontent.com/4229961/33840469-3bcf298e-de52-11e7-96b0-834ec44c7ced.png)

![image](https://user-images.githubusercontent.com/4229961/33840475-4354efc2-de52-11e7-816a-10eb3c123b26.png)

**Comment by BigJArm** [comment]
You can close this bug if you like now, I discovered that if i delete the comic that has out of order pages and then run the scan to re-grab it, the send time it is added to the library it works just fine. Strange quirk, but a pretty easy work around. 

Once again, that you for a wonderful program.

**Comment by hmhrex** [comment]
That's really interesting. I'm going to keep this close this for now, but if it happens again for someone else, please post your experience here so that I can try and resolve what might be happening.

Thanks @BigJArm!
